### PR TITLE
concat embedding

### PR DESCRIPTION
**Pull request by bkodes**

### CODE REVIEW

**Comment by lucidrains** [comment]
hey! so in the paper, they actually sum the embeddings, afaict. that would make sense if the embeddings were to mirror residual latents

**Comment by lucidrains** [comment]
if the PR was to address the todo item, it actually refers to the group dimension from this paper https://arxiv.org/abs/2305.02765

**Comment by bkodes** [comment]
@lucidrains appreciate the clarity and for sending the paper! going to give this another go

**Comment by lucidrains** [comment]
@bkodes ah i think i wasn't being very clear, my mistake. this item may be a bit difficult to contribute to, as it was not in the paper, and just something experimental that i have reasonable confidence would improve things a bit more

**Comment by lucidrains** [comment]
@bkodes oh very cool, so this paper is super relevant then, as it seems to nearly solve TTS.

yes, i would welcome a contribution to the training code!

**Comment by lucidrains** [comment]
@bkodes do you have any thoughts about how to incorporate duration / pitch priors, as they did in the [natural speech line of work](https://github.com/lucidrains/naturalspeech2-pytorch/blob/main/naturalspeech2_pytorch/naturalspeech2_pytorch.py#L271)

**Comment by bkodes** [comment]
@lucidrains yes this paper is extremely relevant so definitely thrilled and think it can solve a lot of current issues with TTS. in terms of incorporating duration/pitch priors let me give it some thought. honestly not really sure it's even necessary given the results but is definitely worth evaluating a bit more

**Comment by lucidrains** [comment]
@bkodes ok sounds good, yea def welcome any contributions to the training code, if open source aligns with your organization's goals

grouped residual VQ support is completed [just now](https://github.com/lucidrains/soundstorm-pytorch/commit/eb32363a904812724efb802f6067f53960d519b6)

**Pull request closed without merging**
